CodeTogether-Inc/CodeTogether-Deployment

- charts/live/templates/deployment.yaml
- charts/live/values.yaml
GitLab SSO provider does not support the "offline_access" scope that CT live sends by default. This change will allow to set the right env variable to not send that scope on the openid request.
> fix: Allow to not send request for offline_access provider scope

- charts/collab/README.md
- charts/collab/values.yaml
- charts/hq/README.md
- charts/hq/templates/deployment.yaml
- charts/hq/values.yaml
- charts/intel/.helmignore
- charts/intel/Chart.yaml
- charts/intel/README.md
- charts/intel/templates/NOTES.txt
- charts/intel/templates/_helpers.tpl
- charts/intel/templates/deployment.yaml
- charts/intel/templates/ingress-class.yaml
- charts/intel/templates/ingress.yaml
- charts/intel/templates/secret-properties.yaml
- charts/intel/templates/secret-pullimage.yaml
- charts/intel/templates/service.yaml
- charts/intel/templates/serviceaccount.yaml
- charts/intel/templates/tests/test-connection.yaml
- charts/intel/values.yaml
- charts/live/README.md
Added detailed README.md files for the following CodeTogether Helm charts:
- CodeTogether HQ
- CodeTogether Live
- CodeTogether Collab
Each README contains comprehensive configuration details, installation instructions, and usage guidelines tailored to the respective chart's `values.yaml` file.
These additions provide clear documentation for deploying and managing CodeTogether applications in Kubernetes environments.
> feat: Add README files for CodeTogether Helm Charts

- charts/live/templates/deployment.yaml
Related to issue https://github.com/CodeTogether-Inc/CodeTogether-Deployment/issues/40
The deployment yaml has an incorrect indentation within the `env` property.
https://github.com/CodeTogether-Inc/CodeTogether-Deployment/blob/dev/charts/live/templates/deployment.yaml#L136
```
{{- if .Values.codetogether.timeZone.enabled }}
- name: CT_TIME_ZONE
value: {{ .Values.codetogether.timeZone.region | quote }}
{{- end }}
- name: CT_LICENSEE
valueFrom:
secretKeyRef:
name: {{ include "codetogether.fullname" . }}-license
key: licensee
- name: CT_MAXCONNECTIONS
valueFrom:
secretKeyRef:
name: {{ include "codetogether.fullname" . }}-license
key: max_connections
```
Which results in this error when `helm` generates the template:
```
Error: YAML parse error on codetogether/templates/deployment.yaml: …
```
> fix(Live): indentation in deployment.yaml

- .github/workflows/helm-template-check.yml
- Introduced a new GitHub Actions workflow (`helm-template-check.yml`)
- Runs `helm template` on `collab`, `hq`, `intel`, and `live` charts
- Uses corresponding `values.yaml` files for validation
- Triggers on pull requests to `main` to ensure chart correctness
- Helps catch Helm template errors before merging changes
Resolves #48
> feat: Add Helm template validation workflow for PR checks

- charts/intel/templates/deployment.yaml
- charts/intel/templates/secret-properties.yaml
- charts/intel/values.yaml
Fixes #63
These changes were requested by Kessel run during our meeting.
1. Support image digest when creating the container, this would guarantee that even if the tag was updated, the image would stay the same.
2. Allow pulling in the cassandra db password from an external secret
> Intel chart improvements: allow image digest & allow cassandra db password from secret

- README.md
- Added CodeTogether Collab and Intel sections to README
- Clarified purpose and functionality of Live, HQ, Collab, and Intel
- Ensured alignment with issue #54
> docs: Update README to include Collab and Intel charts

- charts/intel/README.md
Fixes #57 
- Update readme.md to do not include minimal k8s verison.
> fix: remove k8s version constraint from the readme

- compose/codetogether.nginx
- compose/compose.yaml
- compose/cthq.properties
> fix: Changes for docker compose.

- charts/collab/Chart.yaml
- charts/collab/values.yaml
- charts/intel/Chart.yaml
> Change collab helm chart to use private registry image

- charts/intel/README.md
- charts/intel/templates/deployment.yaml
- charts/intel/templates/secret-properties.yaml
- charts/intel/values.yaml
hqpropertiessecret.enabled, a boolean as to whether an external secret should be referenced
hqpropertiessecret.ref: the name of a kubernetes string in the same namespace that contains the values for hqproperties
because hqproperties contains sensitive information, users may wish to provide their own hqproperties secret.
this secret will need to exist in the same namespace as the intel deployment.
it must contain a key `cthq.properties` that contains a base64 encoded value that contains all the required keys mentioned in the values file
> Allow user to provide their own hqproperties secret

- charts/intel/README.md
- charts/intel/ollama/Dockerfile.ai
- charts/intel/templates/deployment.yaml
- charts/intel/templates/secrets.yaml
- charts/intel/values.yaml
Added support for AI container deployment with bundled and external modes. Configured Helm values to allow users to specify AI providers (OpenAI or custom). Implemented environment variable injection for AI-related configurations. Ensured compatibility with existing Intel deployment. Fixed potential issues with missing secrets and resource allocation.
#3950
> feat(ai): Integrate AI container deployment in Intel chart

- compose/nginx/nginx.conf
> fix: separate SSL certificates

- compose/.env-template
- compose/compose.yaml
- compose/cthq.properties
Single place where we set env variables for both containers.
> Set environment variables via .env file.

- compose/.env-template
- compose/compose.yaml
- compose/nginx/nginx.conf.template
> feat: nginx auto config

- compose/compose.yaml
Missing env file on compose for collab container.
> Missing env file on collab.

- compose/cthq.properties
> cleanup for sso tenants

- charts/intel/templates/deployment.yaml
- charts/intel/values.yaml
Previously, the Helm chart required either 'bundled' or 'external' AI mode to be configured, making it mandatory to include AI integration. This commit introduces a new flag `ai.enabled` to allow disabling AI features entirely, enabling Intel to be deployed without any AI-related containers or resources.
> feat(intel): add option to disable AI integration entirely

- charts/intel/templates/deployment.yaml
- charts/intel/templates/secrets.yaml
- charts/intel/values.yaml
- compose/.env-template
- compose/compose.yaml
- compose/cthq.properties
- compose/nginx/nginx.conf
- compose/nginx/nginx.conf.template
> Merge changes to main.

- compose/.env-template
> Add note to env-template file

- charts/intel/Chart.yaml
- charts/intel/templates/ai-external-secret.yaml
- charts/intel/templates/deployment.yaml
- charts/intel/values.yaml
- Refactored deployment.yaml to reference ai.externalSecret.name when create: false
- Corrected CT_HQ_OLLAMA_AI_API_KEY key to apiKey to match Secret’s stringData
- Updated ai-external-secret.yaml to generate a Secret only when create: true
> Fixes after Testing

- charts/intel/templates/deployment.yaml
- charts/intel/values.yaml
- compose/.env-template
- compose/compose.yaml
Fixes: #157
- values.yaml: introduce `java.trustAllCerts` (default false) to toggle CT_TRUST_ALL_CERTS
- deployment.yaml: inject `CT_TRUST_ALL_CERTS=true` into container env when `trustAllCerts` is enabled
- .env-template: add `CT_TRUST_ALL_CERTS` entry for Docker Compose
- compose.yml: reference `${CT_TRUST_ALL_CERTS}` in codetogether‑intel service
> feat(charts, compose): add CT_TRUST_ALL_CERTS support

- charts/intel/templates/secrets.yaml
Fixes: #160
Wrap the `ai-secrets` Secret manifest with a `.Values.ai.enabled` conditional so it is not rendered when AI is disabled. This prevents clashes with pre-existing `ai-secrets` owned by other releases and keeps templates clean.
> feat(chart): guard `ai-secrets` template behind `ai.enabled`

- compose/keycloak/compose-keycloak-no-nginx.yaml
- compose/keycloak/compose-keycloak.yaml
Fixes #159 
Use health check endpoints.
> Improve keycloak compose health check.

- charts/collab/templates/deployment.yaml
- charts/collab/templates/secret-intel.yaml
- charts/collab/values.yaml
Fixes: #170
- add values: intelsecret.enabled/ref
- conditionally render templates/secret-intel.yaml
- deployment envs read from external secret when enabled(fail if ref missing)
- default unchanged (chart still creates "release"-intel)
> feat(helm-collab): Support optional existing secret for Intel connection

- charts/collab/Chart.yaml
- charts/collab/templates/deployment.yaml
- charts/collab/values.yaml
- charts/intel/Chart.yaml
- charts/intel/templates/deployment.yaml
- charts/intel/values.yaml
This change makes the codetogether-collab and codetogether-intel charts work
out-of-the-box on both vanilla Kubernetes and OpenShift (restricted-v2 SCC),
and adds first-class support for readOnlyRootFilesystem via init containers.
Key changes
-----------
Collab
- Add initContainer `prepare-volatile` to create writable runtime paths when
readOnlyRootFilesystem=true (e.g., /run, /var/log/nginx, /var/cache/nginx,
and the existing /run/volatile/* tree).
- Conditionally handle OpenShift vs vanilla:
- OpenShift: do NOT set runAsUser/runAsGroup/fsGroup; let SCC assign UIDs.
Keep runAsNonRoot and disallow privilege escalation. Avoid chown.
Use `install -d -m 0775/2775` for group-write with sticky set as needed.
- Vanilla: init runs as root (UID 0) to chown created dirs to the non-root
runtime …
> 177 collab intel rofs on open shift avoid run as user 0 support fs group
